# Generated by Django 5.0.1 on 2024-04-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField()),
                ('contraseña', models.CharField(max_length=100)),
                ('imagen_perfil', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
