# Generated by Django 5.0.1 on 2024-04-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='email_usuario',
            field=models.CharField(default='', max_length=100),
        ),
    ]
