# Generated by Django 5.0.1 on 2024-04-26 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_registro_email_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='contraseña',
            new_name='password',
        ),
    ]
