# Generated by Django 5.0.1 on 2024-05-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_rename_contraseña_registro_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='email_usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
