# Generated by Django 5.0.1 on 2024-05-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_alter_registro_email_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='email_usuario',
            field=models.CharField(default='', max_length=100),
        ),
    ]
